version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/example_android_app/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/app/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
